<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HexagonalAdventure.Application\HexagonalAdventure.Application.csproj" />
    <ProjectReference Include="..\HexagonalAdventure.Domain\HexagonalAdventure.Domain.csproj" />
  </ItemGroup>

</Project>
